"""
common_steps.py  +  environment.py (Behave hooks)
==================================================
Shared BDD step definitions and Behave before/after hooks.

- Shared steps used across BCM and UDS feature files
- before_all  : start CANoe session
- before_scenario : reset ECU state
- after_scenario  : capture signal snapshot on failure
- after_all  : save Excel report + upload to Xray

Author : Rakesh Aragodi
"""

import os
import logging
import time

from behave import given, then
from utils.canoe_interface import CANoeInterface
from utils.uds_helper import UDSHelper
from utils.report_generator import ReportGenerator
from utils.xray_client import XrayClient

logger = logging.getLogger(__name__)

CANOE_CONFIG  = os.getenv("CANOE_CONFIG_PATH", r"C:\HIL\configs\BCM_SDV_Test.cfg")
JIRA_PLAN_KEY = os.getenv("JIRA_PLAN_KEY", "BCM-50")


# ══════════════════════════════════════════════════════════════════════
# Behave environment hooks  (behave calls these automatically)
# ══════════════════════════════════════════════════════════════════════

def before_all(context):
    """Session setup — start CANoe once for all scenarios."""
    logging.basicConfig(level=logging.INFO)
    context.logger = logging.getLogger("BDD")

    context.logger.info("=== BEHAVE SESSION SETUP ===")
    context.canoe = CANoeInterface()
    context.canoe.open(CANOE_CONFIG)
    context.canoe.start_measurement(stabilise_seconds=2.0)

    context.uds            = UDSHelper(context.canoe)
    context.report         = ReportGenerator(project="JLR SDV BCM — BDD")
    context.xray           = XrayClient()
    context.failed_scenarios = []


def after_all(context):
    """Session teardown — save report, upload to Xray, stop CANoe."""
    context.logger.info("=== BEHAVE SESSION TEARDOWN ===")

    # Save Excel report
    report_path = context.report.save(output_dir="reports")
    context.logger.info("Report saved: %s", report_path)

    # Upload JUnit XML to Xray (generated by behave --junit)
    junit_xml = "reports/TESTS-features.xml"
    if os.path.exists(junit_xml):
        try:
            execution_key = context.xray.upload_junit_xml(
                xml_path=junit_xml,
                plan_key=JIRA_PLAN_KEY,
                summary=f"BDD Regression — {context.report._build}",
            )
            context.logger.info("Xray execution created: %s", execution_key)
        except Exception as exc:
            context.logger.warning("Xray upload failed (non-blocking): %s", exc)

    context.canoe.stop_measurement()


def before_scenario(context, scenario):
    """Reset ECU state before each scenario."""
    context.logger.info("--- SCENARIO: %s [%s] ---", scenario.name, ", ".join(scenario.tags))
    # Reset vehicle speed
    context.canoe.set_signal_value("Chassis", "VehicleInfo", "VehicleSpeed_kph", 0)
    # Clear DTCs
    context.uds.clear_dtc(group_of_dtc=0xFFFFFF)
    time.sleep(0.2)


def after_scenario(context, scenario):
    """On failure — capture signal snapshot for diagnosis."""
    if scenario.status == "failed":
        context.logger.warning("SCENARIO FAILED: %s", scenario.name)
        try:
            # Capture key signal values for the report
            snapshot = {
                "DoorLock_FL"  : context.canoe.get_signal_value("Comfort", "DoorLockStatus", "DoorLock_Status_FL"),
                "VehicleSpeed" : context.canoe.get_signal_value("Chassis", "VehicleInfo", "VehicleSpeed_kph"),
            }
            context.logger.warning("Signal snapshot at failure: %s", snapshot)
        except Exception:
            pass  # Don't let snapshot capture mask the original failure


# ══════════════════════════════════════════════════════════════════════
# Common shared steps
# ══════════════════════════════════════════════════════════════════════

@given('the ECU is connected via CANoe diagnostic channel')
def step_ecu_connected(context):
    heartbeat = context.canoe.get_signal_value("Comfort", "BCM_Status", "BCM_Heartbeat")
    assert heartbeat is not None, "ECU not detected on diagnostic channel"


@given('the ECU is in the default diagnostic session (0x01)')
def step_default_session(context):
    response = context.uds.session_control(0x01)
    assert response.is_positive, "Could not switch to default session"


@given('the ECU is in extended diagnostic session (0x03)')
def step_extended_session(context):
    response = context.uds.session_control(0x03)
    assert response.is_positive, "Could not switch to extended diagnostic session"


@then('the positive response SID should be {expected_sid}')
def step_check_positive_sid(context, expected_sid):
    expected = int(expected_sid, 16)
    response = context.last_response
    assert response.is_positive, (
        f"Expected positive response 0x{expected:02X} but got negative: "
        f"NRC=0x{response.nrc:02X} [{response.nrc_description}]"
    )
    assert response.positive_sid == expected, (
        f"Response SID mismatch: got 0x{response.positive_sid:02X}, "
        f"expected 0x{expected:02X}"
    )
